### ISSUE TITLE
question about reweight

### ISSUE THREAD

**Issue by 943fansi** [junwoopark92/ECMLPKDD2023-ReLD#1]
Could you please tell me the code of reweight function?

**Comment by junwoopark92** [comment]
Hi, you can see the code of reweighting function below.

https://github.com/junwoopark92/ECMLPKDD2023-ReLD/blob/a6400f3e648874f1d91236253124829648c61e39/data_provider/data_loader.py#L270

**Comment by 943fansi** [comment]
@junwoopark92 Thanks for your reply.
